#!/usr/bin/zsh
source .venv/bin/activate

echo "checking packages..."
packages=$(pip --disable-pip-version-check list --outdated --format=json)
echo "found: "$packages

if [ $packages != '[]'  ]
then
    echo "updating..."
    echo $packages | python -c "import json, sys; print('\n'.join([x['name'] for x in json.load(sys.stdin)]))"  | xargs -n1 pip install -U
else
    echo "nothing to update"
fi

deactivate

